#!/usr/bin/env zsh

local sinks=($(pactl list sinks | grep Name: | sed 's/\tName: //'))
local newSink=${sinks[$((${sinks[(Ie)$(pactl get-default-sink)]}+1))]}
if [[ $newSink == "" ]]; then
  pactl set-default-sink ${sinks[1]}
else
  pactl set-default-sink $newSink
fi
