#!/usr/bin/env zsh

local blacklist=("alsa_output.pci-0000_03_00.1.hdmi-stereo")
local sinks=($(pactl list sinks | grep Name: | sed 's/\tName: //'))
local newSink=${sinks[$((${sinks[(Ie)$(pactl get-default-sink)]}+1))]}
while [[ ${blacklist[(Ie)$newSink]} != 0 ]]; do
  newSink=${sinks[$((${sinks[(Ie)$(pactl get-default-sink)]}+1))]}
done
if [[ $newSink == "" ]]; then
  pactl set-default-sink ${sinks[1]}
else
  pactl set-default-sink $newSink
fi
