#!/usr/bin/env zsh

local function cloneLocalParseURL() {
  if rg -q '/' <<< $1; then
    if rg -q '^http' <<< $1; then
      print $1
    else
      print "https://github.com/$1"
    fi
  else
    print "https://github.com/$(whoami)/$1"
  fi
}

if [[ $1 == (-h|--help) ]]; then
  msg="$(sed -e 's/^[ ]*| //m' <<'--------------------'
    | A script for cloning git repos
    | 
    | %UUsage:%u %Bclone%b <REPOSITORY> [PATH] [<ARGS>]
    | 
    | %UArguments:%u
    |   %B<REPOSITORY>%b\tRepository URL
    | 
    |   %B[PATH]%b\tRoot directory to clone to. Defaults to ~/Repos.
    | 
    |   %B<ARGS>%b\tGit clone args. See %Ugit-clone(1)%u for more info.
--------------------
    )"
  print -P $msg
else
  repo=$(cloneLocalParseURL $1 | sed -r 's|.*/([^/]+/[^/]+)(\.git)?$|\1|')
  if [[ "$2" == -* ]]; then
    git clone $(echo "$@[2,-1] --") $(cloneLocalParseURL $1) "$HOME/Repos/$repo"
    cd "$HOME/Repos/$repo"
  elif [[ -e $2 ]]; then
    git clone $(echo "$@[3,-1] --") $(cloneLocalParseURL $1) "$2/$repo"
    cd "$2/Repos/$repo"
  else
    git clone $(cloneLocalParseURL $1) "$HOME/Repos/$repo"
    cd "$HOME/Repos/$repo"
  fi
fi

unfunction cloneLocalParseURL

