#!/usr/bin/env zsh

image="[debian]
image=debian:testing
additional_packages=\"hyfetch bat ripgrep\""
if [[ $VENDOR = debian ]]; then
  print "Already in container"
  exit 1
fi
if podman container exists debian; then
  if ! distrobox enter debian --additional-flags "--env SSH_CONNECTION=$SSH_CONNECTION"; then
    podman rm debian
    distrobox assemble create --file /dev/stdin <<< $image
  fi
else
  distrobox assemble create --file /dev/stdin <<< $image
fi

