#!/usr/bin/env zsh

ln -s ~/.steam ~/Steam
ln -s ~/.wine ~/Wine

cat > ~/.config/kdeglobals << EOF
[General]
TerminalApplication=kitty

[Icons]
Theme=Everforest
EOF

cat > ~/.config/dolphinrc << EOF
MenuBar=Disabled

[General]
ConfirmClosingMultipleTabs=false
GlobalViewProps=false
RememberOpenedTabs=false

[IconsMode]
IconSize=64

[KFileDialog Settings]
Places Icons Auto-resize=false
Places Icons Static Size=22

[MainWindow]
MenuBar=Disabled

[PreviewSettings]
Plugins=appimagethumbnail,audiothumbnail,blenderthumbnail,comicbookthumbnail,cursorthumbnail,djvuthumbnail,ebookthumbnail,exrthumbnail,imagethumbnail,jpegthumbnail,kraorathumbnail,windowsexethumbnail,windowsimagethumbnail,mobithumbnail,opendocumentthumbnail,gsthumbnail,rawthumbnail,svgthumbnail

[UiSettings]
ColorScheme=*

[VersionControl]
enabledPlugins=Git
EOF

