#!/usr/bin/env zsh

function dir() {
mkdir ~/$1
if [[ $2 ]]; then cat > ~/$1/.directory << EOF
[Desktop Entry]
Icon=$2
EOF
fi
}

dir Documents
dir Downloads
dir Games folder-games
dir Music
dir Pictures
dir Repos folder-git
dir Videos
dir .steam folder-steam
dir .wine folder-wine

ln -s ~/.steam ~/Steam
ln -s ~/.wine ~/Wine

cat > ~/.config/kdeglobals << EOF
[General]
TerminalApplication=kitty

[Icons]
Theme=Colloid-Dark

[KDE]
ShowDeleteCommand=true

[KFileDialog Settings]
Allow Expansion=false
Automatically select filename extension=true
Breadcrumb Navigation=false
Decoration position=2
LocationCombo Completionmode=5
PathCombo Completionmode=5
Show Bookmarks=false
Show Full Path=false
Show Inline Previews=true
Show Preview=false
Show Speedbar=true
Show hidden files=false
Sort by=Date
Sort directories first=true
Sort hidden files last=false
Sort reversed=true
View Style=Simple

[PreviewSettings]
EnableRemoteFolderThumbnail=false
MaximumRemoteSize=0
EOF

cat > ~/.config/dolphinrc << EOF
MenuBar=Disabled

[DetailsMode]
PreviewSize=22

[ExtractDialog]
2 screens: Window-Maximized=true

[General]
ConfirmClosingMultipleTabs=false
GlobalViewProps=false
RememberOpenedTabs=false
Version=202

[IconsMode]
IconSize=64

[KFileDialog Settings]
Places Icons Auto-resize=false
Places Icons Static Size=22

[KPropertiesDialog]
2 screens: Window-Maximized=true

[MainWindow]
MenuBar=Disabled

[PreviewSettings]
Plugins=appimagethumbnail,audiothumbnail,blenderthumbnail,comicbookthumbnail,cursorthumbnail,djvuthumbnail,ebookthumbnail,exrthumbnail,imagethumbnail,jpegthumbnail,kraorathumbnail,windowsexethumbnail,windowsimagethumbnail,mobithumbnail,opendocumentthumbnail,gsthumbnail,rawthumbnail,svgthumbnail

[UiSettings]
ColorScheme=*

[VersionControl]
enabledPlugins=Git

[ViewPropertiesDialog]
2 screens: Window-Maximized=true
EOF

