#!/usr/bin/env zsh

function dir() {
mkdir ~/$1
if [[ $2 ]]; then cat > ~/$1/.directory << EOF
[Desktop Entry]
Icon=$2
EOF
fi
}

dir Documents
dir Downloads
dir Games folder-games
dir Music
dir Pictures
dir Repos folder-git
dir Videos
dir .steam folder-steam
dir .wine folder-wine

ln -s ~/.steam ~/Steam
ln -s ~/.wine ~/Wine

cat > ~/.config/kdeglobals << EOF
[General]
TerminalApplication=kitty

[Icons]
Theme=Everforest
EOF

cat > ~/.config/dolphinrc << EOF
MenuBar=Disabled

[General]
ConfirmClosingMultipleTabs=false
GlobalViewProps=false
RememberOpenedTabs=false

[IconsMode]
IconSize=64

[KFileDialog Settings]
Places Icons Auto-resize=false
Places Icons Static Size=22

[MainWindow]
MenuBar=Disabled

[PreviewSettings]
Plugins=appimagethumbnail,audiothumbnail,blenderthumbnail,comicbookthumbnail,cursorthumbnail,djvuthumbnail,ebookthumbnail,exrthumbnail,imagethumbnail,jpegthumbnail,kraorathumbnail,windowsexethumbnail,windowsimagethumbnail,mobithumbnail,opendocumentthumbnail,gsthumbnail,rawthumbnail,svgthumbnail

[UiSettings]
ColorScheme=*

[VersionControl]
enabledPlugins=Git
EOF

