#!/usr/bin/env zsh
windows=$(hyprctl clients -j | jq '.[].title' -r)
if [[ $(($(cat /tmp/$1)+5400)) -lt $(date +%s) ]] || ! [ -e /tmp/$1 ] && islive $1 && print $windows | grep "$2 - Twitch — LibreWolf"; then
  if [[ $(notify-send --icon="/home/readf0x/Pictures/$1.png" "$1 is live!" "" --action="WATCH"="Watch Stream" --action="DISMISS"="Dismiss" --expire-time=2000) == "WATCH" ]]; then
    xdg-open "https://twitch.tv/$1"
  fi
  date '+%s' > /tmp/$1
fi

