#!/usr/bin/env zsh

if [[ $1 == "notify" ]]; then
  notify-send "Current Player:" $(cat ~/.player) -i music-app-symbolic -t 2000
else
  playerctl --player=$(cat ~/.player) --format="{{playerName}} - {{title}}" metadata
fi

