#!/usr/bin/env fish

cd ~/.config
cp dolphinrc dolphinrc.bak
cp dolphinrc.reactions dolphinrc

cd ~/.local/state
cp dolphinstaterc dolphinstaterc.bak
cp dolphinstaterc.reactions dolphinstaterc

dolphin ~/Pictures/Reactions & disown
sleep 1

cd ~/.config
cp dolphinrc dolphinrc.reactions
cp dolphinrc.bak dolphinrc

cd ~/.local/state
cp dolphinstaterc dolphinstaterc.reactions
cp dolphinstaterc.bak dolphinstaterc

