#!/usr/bin/env zsh

function parseURL() {
  if rg -q '/' <<< $1; then
    if rg -q '^http' <<< $1; then
      print $1
    else
      print "https://github.com/$1"
    fi
  else
    print "https://github.com/$(whoami)/$1"
  fi
}

if [[ $1 == -h ]] || [[ $1 == --help ]]; then
  msg="$(sed -e 's/^[ ]*| //m' <<'--------------------'
    | A script for cloning git template repos
    | 
    | %UUsage:%u %Bclone%b <TEMPLATE> [PATH]
    | 
    | %UArguments:%u
    |   %B<TEMPLATE>%b\tRepository URL, accepts `username/repo' and `repo'. Defaults to github for hosting and your username.
    | 
    |   %B[PATH]%b\tDirectory to clone to.
--------------------
    )"
  print -P $msg
else
  git clone $(parseURL $1) $2
  if [ $2 ]; then
    cd $2
  else
    cd $(rg -o '[^/]*$' <<< $1)
  fi
  git remote rm origin
fi

